kind: pipeline
name: default

steps:
  - name: FrontEnd Eval
    image: node
    commands:
      - npm install -g enzyme
      - npm install -g jest
      - npm install -g enzyme-adapter-react-16
      - git clone https://github.com/unsortedArray/blog-app-FE-test-cases.git
      - cd blog-app-FE-test-cases
      - cp -a ./ ../src/components/__tests__
      - npm install -g enzyme
      - npm install -g jest
      - cd ..
      - npm install
      - npm run test --exit 
